version: '3.8'

services: 
  mongo: 
    ports:
      - ${MONGO_PORT}:27017

  #uncomment this section if you want a local mongo-express
  #mongo-express:
  #  image: mongo-express
  #  restart: always
  #  ports:
  #    - ${MONGO_EXPRESS_PORT}:8081
  #  environment:
  #    - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
  #    - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  #    - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_EXPRESS_HOST}:${MONGO_EXPRESS_PORT}/