version: '3.8'

services: 
  mongo: 
    image: mongo:latest
    restart: always
    env_file:
      - .env
    volumes:
      - "./config/mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro"
      - "db:/data/db"
      - "configdb:/data/configdb"

volumes:
  db:
  configdb: