version: '3.8'

services: 
  mongo: 
    image: mongo:latest
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    env_file:
      - .env
    volumes:
      - "./config/mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro"
      - "db:/data/db"
      - "configdb:/data/configdb"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
  
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   restart: always
  #   ports:
  #     - ${RABBITMQ_MANAGEMENT_PORT}:15672
  #     - ${RABBITMQ_PORT}:5672


volumes:
  db:
  configdb: